import { chromium } from '@playwright/test';
import { resolve } from 'node:path';
const out = process.argv[2] ?? '/tmp/shots';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
await page.goto('file://' + resolve('dist/index.html'));
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/30-file-profiles.png` });
await page.click('.profile-card');
await page.fill('.modal input[type=text]', 'Léa');
await page.click('.modal .btn-primary');
await page.waitForTimeout(400);
await page.click('.menu-card.accent');
await page.click('.mode-card:nth-child(3) .btn');
await page.waitForTimeout(4500);
const st = await page.evaluate(() => ({ phase: window.mp2game.phase, asteroids: window.mp2game.asteroids.length, font: document.fonts.check('16px Orbitron') }));
await page.screenshot({ path: `${out}/31-file-game.png` });
console.log('file:// state', JSON.stringify(st));
console.log(JSON.stringify(errors));
await browser.close();
